// Client-side IVAC codec extractor. Runs entirely in the browser:
//   - the obfuscated bundle executes in a sandboxed <iframe> (no server),
//   - the codec is probed INSIDE the iframe (its functions can't cross the
//     postMessage boundary), and only plain-data results come back,
//   - emit/scan run on the main thread.
// No backend, no timeouts, hostable as static files anywhere.

export const CHARSET =
  '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ-_';

const dedupe = (arr, k) => {
  const s = new Set(), o = [];
  for (const x of arr) { const key = k(x); if (s.has(key)) continue; s.add(key); o.push(x); }
  return o;
};

// ----------------------------------------------------------- bundle scan -----
export function scanBundle(src) {
  const codecModuleVars = dedupe(
    [...src.matchAll(/([A-Za-z_$][\w$]*)\s*=\s*Object\.freeze\(Object\.defineProperty\(\{__proto__:null,\s*decryptText:[A-Za-z_$][\w$]*,\s*encryptText:[A-Za-z_$][\w$]*\}/g)].map((m) => m[1]),
    (v) => v);
  const callSiteConfigs = dedupe(
    [...src.matchAll(/,\s*([A-Za-z_$][\w$]*)\s*,\s*(\d{1,2})\s*,\s*(\d{1,3})\)\)/g)]
      .map((m) => ({ keyExpr: m[1], startAt: +m[2], length: +m[3] }))
      .filter((c) => c.startAt >= 0 && c.startAt <= 24 && c.length >= 6 && c.length <= 48),
    (c) => c.keyExpr + '|' + c.startAt + '|' + c.length);
  const keyVars = dedupe([
    ...[...src.matchAll(/\b([A-Za-z_$][\w$]*)\s*=\s*(?:[A-Za-z_$][\w$]*\([^()]*\)|"[^"]*")(?:\+(?:[A-Za-z_$][\w$]*\([^()]*\)|"[^"]*")){4,}/g)].map((m) => m[1]),
    ...callSiteConfigs.map((c) => c.keyExpr),
  ], (v) => v);
  const families = [];
  if (/3\.99/.test(src)) families.push('logistic-map');
  if (/%\s*67/.test(src)) families.push('polynomial-mod-67');
  if (!families.length) families.push('unknown');
  return { codecModuleVars, callSiteConfigs, keyVars, families };
}

export function gatherRoutes(src) {
  return [...new Set([...src.matchAll(/(auth\/sign-?in[\w-]*|auth\/signup|slots\/reserveSlot|slots\/[\w-]+|auth\/[\w-]+)/g)].map((m) => m[1]))].slice(0, 12);
}

// ------------------------------------------------------------ emit codec -----
export function emitCodec(codecs, families, fname = '') {
  const ok = codecs.filter((c) => c.verified && c.model);
  if (!ok.length) return '';
  const used = new Set();
  for (const c of ok) { let b = c.name, n = b, i = 2; while (used.has(n)) n = `${b}_${i++}`; used.add(n); c.emitName = n; }
  const kinds = new Set(ok.map((c) => c.model.kind));

  let s = `// AUTO-GENERATED by IVAC extractor${fname ? ' from ' + fname : ''}
// Behaviour captured from the bundle's own codec (probed over the full alphabet)
// and verified against it. Generator families seen: ${families.join(', ')}

const CHARSET =
  '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ-_';

`;
  if (kinds.has('shift')) s += `function applyShift(token, shifts, startAt, sign) {
  const p = Math.max(0, Math.min(startAt, token.length));
  const w = Math.max(0, Math.min(shifts.length, Math.max(0, token.length - p)));
  if (w === 0) return token;
  const ch = token.slice(p, p + w).split('');
  for (let i = 0; i < w; i++) { const x = CHARSET.indexOf(ch[i]); if (x !== -1) ch[i] = CHARSET[(((x + sign * shifts[i]) % 64) + 64) % 64]; }
  return token.slice(0, p) + ch.join('') + token.slice(p + w);
}

`;
  if (kinds.has('sub')) s += `function applySub(token, table, startAt, length, sign) {
  const p = Math.max(0, Math.min(startAt, token.length));
  const w = Math.max(0, Math.min(length, Math.max(0, token.length - p)));
  if (w === 0) return token;
  const ch = token.slice(p, p + w).split('');
  for (let i = 0; i < w; i++) { const x = CHARSET.indexOf(ch[i]); if (x !== -1) ch[i] = CHARSET[sign > 0 ? table[x] : table.indexOf(x)]; }
  return token.slice(0, p) + ch.join('') + token.slice(p + w);
}

`;
  if (kinds.has('tables')) s += `function applyTables(token, tables, startAt, sign) {
  const p = Math.max(0, Math.min(startAt, token.length));
  const w = Math.max(0, Math.min(tables.length, Math.max(0, token.length - p)));
  if (w === 0) return token;
  const ch = token.slice(p, p + w).split('');
  for (let i = 0; i < w; i++) { const x = CHARSET.indexOf(ch[i]); if (x !== -1) ch[i] = CHARSET[sign > 0 ? tables[i][x] : tables[i].indexOf(x)]; }
  return token.slice(0, p) + ch.join('') + token.slice(p + w);
}

`;
  const exp = [];
  for (const c of ok) {
    const U = c.emitName.toUpperCase().replace(/[^A-Z0-9]/g, '_'), m = c.model;
    s += `// ${c.emitName} — ${m.kind}, startAt ${c.startAt}, length ${c.length}, key ${JSON.stringify(c.key)}\n`;
    if (m.kind === 'shift') {
      s += `const ${U}_SHIFTS = [${m.shifts.join(',')}];\nconst ${c.emitName}Encrypt = (t) => applyShift(t, ${U}_SHIFTS, ${c.startAt}, +1);\nconst ${c.emitName}Decrypt = (t) => applyShift(t, ${U}_SHIFTS, ${c.startAt}, -1);\n\n`;
      exp.push(`  ${c.emitName}Encrypt, ${c.emitName}Decrypt, ${U}_SHIFTS`);
    } else if (m.kind === 'sub') {
      s += `const ${U}_TABLE = [${m.table.join(',')}];\nconst ${c.emitName}Encrypt = (t) => applySub(t, ${U}_TABLE, ${c.startAt}, ${c.length}, +1);\nconst ${c.emitName}Decrypt = (t) => applySub(t, ${U}_TABLE, ${c.startAt}, ${c.length}, -1);\n\n`;
      exp.push(`  ${c.emitName}Encrypt, ${c.emitName}Decrypt, ${U}_TABLE`);
    } else {
      s += `const ${U}_TABLES = ${JSON.stringify(m.tables)};\nconst ${c.emitName}Encrypt = (t) => applyTables(t, ${U}_TABLES, ${c.startAt}, +1);\nconst ${c.emitName}Decrypt = (t) => applyTables(t, ${U}_TABLES, ${c.startAt}, -1);\n\n`;
      exp.push(`  ${c.emitName}Encrypt, ${c.emitName}Decrypt, ${U}_TABLES`);
    }
  }
  const helpers = ['CHARSET', kinds.has('shift') && 'applyShift', kinds.has('sub') && 'applySub', kinds.has('tables') && 'applyTables'].filter(Boolean);
  s += 'export {\n  ' + helpers.join(', ') + ',\n' + exp.join(',\n') + '\n};\n';
  return s;
}

// ---------------------------------------------- iframe-side capture library --
// Injected verbatim into the sandboxed iframe (runs alongside the bundle).
const HARNESS_LIB = `
var CHARSET='0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ-_';
function applyModel(token,model,startAt,sign){
  var len=model.len,p=Math.max(0,Math.min(startAt,token.length)),w=Math.max(0,Math.min(len,Math.max(0,token.length-p)));
  if(w===0)return token; var ch=token.slice(p,p+w).split('');
  for(var i=0;i<w;i++){var x=CHARSET.indexOf(ch[i]); if(x===-1)continue; var y;
    if(model.kind==='shift'){y=(((x+sign*model.shifts[i])%64)+64)%64;}
    else{var tbl=model.kind==='sub'?model.table:model.tables[i]; y=sign>0?tbl[x]:tbl.indexOf(x);}
    ch[i]=CHARSET[y];}
  return token.slice(0,p)+ch.join('')+token.slice(p+w);
}
function captureModel(mod,key,startAt,length){
  if(!mod||typeof mod.encryptText!=='function')return null;
  try{
    var N=length,tables=[]; for(var i=0;i<N;i++)tables.push(new Array(64));
    for(var v=0;v<64;v++){
      var probe=repeat('x',startAt)+repeat(CHARSET[v],N);
      var win=mod.encryptText(probe,key,startAt,N).slice(startAt,startAt+N);
      if(win.length!==N)return null;
      for(var i=0;i<N;i++){var o=CHARSET.indexOf(win[i]); if(o<0)return null; tables[i][v]=o;}
    }
    for(var i=0;i<N;i++){var seen={},cnt=0; for(var v=0;v<64;v++){if(!seen[tables[i][v]]){seen[tables[i][v]]=1;cnt++;}} if(cnt!==64)return null;}
    var isShift=true,shifts=[];
    for(var i=0;i<N&&isShift;i++){var k=tables[i][0]%64; for(var v=0;v<64;v++){if(tables[i][v]!==(v+k)%64){isShift=false;break;}} shifts.push(k);}
    if(isShift)return {kind:'shift',len:N,shifts:shifts};
    var posIndep=true;
    for(var i=1;i<N&&posIndep;i++)for(var v=0;v<64;v++){if(tables[i][v]!==tables[0][v]){posIndep=false;break;}}
    if(posIndep)return {kind:'sub',len:N,table:tables[0]};
    return {kind:'tables',len:N,tables:tables};
  }catch(e){return null;}
}
function verify(mod,key,startAt,length,model){
  try{
    var tok='1.'+repeat2('aB3xZ-_qrs0u',18);
    var real=mod.encryptText(tok,key,startAt,length);
    var baked=applyModel(tok,model,startAt,1); if(real!==baked)return false;
    var back=typeof mod.decryptText==='function'?mod.decryptText(baked,key,startAt,length):applyModel(baked,model,startAt,-1);
    return back===tok;
  }catch(e){return false;}
}
function modelPreview(m){ if(!m)return null; if(m.kind==='shift')return m.shifts; if(m.kind==='sub')return m.table; return m.tables[0]; }
function repeat(s,n){var o='';for(var i=0;i<n;i++)o+=s;return o;}
function repeat2(s,n){var o='';for(var i=0;i<n;i++)o+=s;return o;}
`;

// build the bundle injection (capture modules/configs/keys) — like the server
function injectBundle(src, scan, configs) {
  const ci = src.lastIndexOf('}()');
  if (ci === -1) throw new Error('bundle is not a self-executing IIFE');
  const callExprs = (configs || []).map((c, i) =>
    `try{self.__C[${i}]={key:(${c.keyExpr}),startAt:${c.startAt},length:${c.length}}}catch(e){}`);
  const keyExprs = (scan.keyVars || []).map((v) => `try{self.__K[${JSON.stringify(v)}]=${v}}catch(e){}`);
  const inj =
    ';try{self.__MODS={' + scan.codecModuleVars.map((v) => `${JSON.stringify(v)}:${v}`).join(',') + '};' +
    'self.__C={};' + callExprs.join('') +
    'self.__K={};' + keyExprs.join('') +
    '}catch(e){self.__E=String(e)};';
  return src.slice(0, ci) + inj + src.slice(ci);
}

function runIframe(innerScript, timeoutMs = 25000) {
  return new Promise((resolve) => {
    const tk = 'cap_' + Math.random().toString(36).slice(2);
    const html =
      '<!doctype html><meta charset=utf-8><div id="root"></div><div id="app"></div><script>' +
      'self.__TK=' + JSON.stringify(tk) + ';self.__MODS=null;self.__C=null;self.__K=null;self.__E=null;self.__RUNERR=null;' +
      'window.onerror=function(){return true};' + innerScript + '<\/script>';
    const iframe = document.createElement('iframe');
    iframe.sandbox = 'allow-scripts';
    iframe.style.display = 'none';
    iframe.srcdoc = html;
    let done = false;
    const finish = (data) => { if (done) return; done = true; window.removeEventListener('message', onMsg); iframe.remove(); resolve(data); };
    const onMsg = (ev) => { if (ev.data && ev.data.t === tk) finish(ev.data); };
    window.addEventListener('message', onMsg);
    document.body.appendChild(iframe);
    setTimeout(() => finish({ t: tk, codecs: [], err: 'timeout — the bundle did not finish in the iframe' }), timeoutMs);
  });
}

// ----------------------------------------------------- AI-config extraction --
// configs: [{keyExpr,startAt,length,name}] located by the AI (probed + verified)
export async function extractWithConfigs(src, configs, families) {
  const scan = scanBundle(src);
  if (!scan.codecModuleVars.length) return { codecs: [], families, err: 'No codec module found in bundle.' };
  const patched = injectBundle(src, scan, configs);
  const names = JSON.stringify(configs.map((c) => c.name || `codec_${c.startAt}_${c.length}`));
  const harness =
    'try{' + patched + '}catch(e){self.__RUNERR=String(e)}' +
    '(function(){' + HARNESS_LIB +
    'var names=' + names + ';var mods=self.__MODS||{},mv=Object.keys(mods).filter(function(k){return mods[k]&&typeof mods[k].encryptText==="function"});' +
    'var out=[],call=self.__C||{};' +
    'for(var k in call){var c=call[k];if(!c||typeof c.key!=="string"||c.key.length<8)continue;var name=names[+k]||("codec_"+c.startAt+"_"+c.length);var best=null;' +
    'for(var i=0;i<mv.length;i++){var model=captureModel(mods[mv[i]],c.key,c.startAt,c.length);if(!model)continue;var ok=verify(mods[mv[i]],c.key,c.startAt,c.length,model);' +
    'var rec={name:name,key:c.key,startAt:c.startAt,length:c.length,version:null,model:model,kind:model.kind,verified:ok,source:"ai+callsite",preview:modelPreview(model)};' +
    'if(ok){best=rec;break;}if(!best)best=rec;}if(best)out.push(best);}' +
    'parent.postMessage({t:self.__TK,codecs:out,err:self.__E||null},"*");' +
    '})();';
  const res = await runIframe(harness);
  return { codecs: res.codecs || [], families, err: res.err };
}

// --------------------------------------------------------- sample extraction --
export async function extractFromSample(src, sample, families) {
  const raw = String(sample?.raw || ''), encoded = String(sample?.encoded || '');
  if (!raw || !encoded) return { codecs: [], families, err: 'Provide both raw and encoded token.' };
  if (raw.length !== encoded.length) return { codecs: [], families, err: 'raw and encoded differ in length — not a windowed transform (wrong pair?).' };
  let lo = -1, hi = -1;
  for (let i = 0; i < raw.length; i++) if (raw[i] !== encoded[i]) { if (lo < 0) lo = i; hi = i; }
  if (lo < 0) return { codecs: [], families, err: 'raw and encoded are identical — nothing transformed.' };

  const scan = scanBundle(src);
  const patched = scan.codecModuleVars.length ? injectBundle(src, scan, scan.callSiteConfigs) : null;
  const P = { raw, encoded, lo, hi, callWindows: scan.callSiteConfigs.map((c) => [c.startAt, c.length]) };
  const harness =
    (patched ? 'try{' + patched + '}catch(e){self.__RUNERR=String(e)}' : '') +
    '(function(){' + HARNESS_LIB +
    'var P=' + JSON.stringify(P) + ';var raw=P.raw,enc=P.encoded,lo=P.lo,hi=P.hi;' +
    'var mods=self.__MODS||{},mv=Object.keys(mods).filter(function(k){return mods[k]&&typeof mods[k].encryptText==="function"});' +
    'var keys={};var K=self.__K||{},C=self.__C||{};' +
    'for(var k in K){var val=K[k];if(typeof val==="string"&&val.length>=16&&val.length<=96)keys[val]=1;}' +
    'for(var k in C){if(C[k]&&typeof C[k].key==="string")keys[C[k].key]=1;}' +
    'var wins={};function addW(sa,ln){if(sa>=0&&ln>0&&sa+ln<=raw.length)wins[sa+"/"+ln]={s:sa,l:ln};}' +
    'for(var i=0;i<P.callWindows.length;i++)addW(P.callWindows[i][0],P.callWindows[i][1]);' +
    'addW(lo,hi-lo+1);for(var s=Math.max(0,lo-2);s<=lo;s++)for(var ex=0;ex<=6;ex++)addW(s,hi-s+1+ex);' +
    'var keyList=Object.keys(keys),winList=Object.keys(wins);' +
    'for(var mi=0;mi<mv.length;mi++){var mod=mods[mv[mi]];' +
    ' for(var ki=0;ki<keyList.length;ki++){var key=keyList[ki];' +
    '  for(var wi=0;wi<winList.length;wi++){var W=wins[winList[wi]];' +
    '   var model=captureModel(mod,key,W.s,W.l);if(!model)continue;var out;try{out=applyModel(raw,model,W.s,1);}catch(e){continue;}' +
    '   if(out===enc){var name=(W.s===8&&W.l===29)?"signin":(W.s===6&&W.l===17)?"reserve":("codec_"+W.s+"_"+W.l);' +
    '    parent.postMessage({t:self.__TK,codecs:[{name:name,key:key,startAt:W.s,length:W.l,version:null,model:model,kind:model.kind,verified:true,source:"sample",preview:modelPreview(model)}],note:"Matched real token sample at startAt "+W.s+", length "+W.l+"."},"*");return;}}}}' +
    // derived-shift fallback (baked standalone shift ciphers)
    'var sa=lo,len=hi-lo+1,shifts=[],okS=true;' +
    'for(var i=0;i<len;i++){var x=CHARSET.indexOf(raw[sa+i]),y=CHARSET.indexOf(enc[sa+i]);if(x<0||y<0){okS=false;break;}shifts.push(((y-x)%64+64)%64);}' +
    'if(okS){var model={kind:"shift",len:len,shifts:shifts};var name=(sa===8&&len===29)?"signin":(sa===6&&len===17)?"reserve":("codec_"+sa+"_"+len);' +
    ' parent.postMessage({t:self.__TK,codecs:[{name:name,key:"(no key — derived from sample)",startAt:sa,length:len,version:null,model:model,kind:"shift",verified:true,source:"sample-derived-shift",preview:shifts}],note:"No codec module reproduced the sample; derived a position-shift model directly from the pair (startAt "+sa+", length "+len+"). Exact if the cipher is a position shift."},"*");return;}' +
    'parent.postMessage({t:self.__TK,codecs:[],note:"No key/window reproduced the sample, and it is not a plain position shift."},"*");' +
    '})();';
  const res = await runIframe(harness);
  return { codecs: res.codecs || [], families, note: res.note, err: res.err };
}
